backend:
  name: git-gateway
  branch: main # or 'master', depending on your repo

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "src/content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "price", label: "Price" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
